name: shop
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http:
  json_annotation: ^2.4.0
  shared_preferences: ^0.5.6+1
  simple_animations:
  page_transition:
  division:
  intl:
  transformer_page_view: ^0.1.6
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  firebase_messaging: ^6.0.13
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  flutter_cupertino_localizations: ^1.0.1
  velocity_x: ^0.2.0
  provider: ^4.0.4
  badges:
  flutter_swiper: ^1.1.6
  dio:
  sqflite: any
  path_provider: ^1.6.5
  lottie: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/shop-logo-big.png
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ExpoArabic
      fonts:
        - asset: fonts/ExpoArabic-Book.ttf

    - family: Al-Jazeera
      fonts:
        - asset: fonts/Al-Jazeera-Arabic-Bold.ttf
